// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThietBiDienTu_2.Models;

#nullable disable

namespace ThietBiDienTu_2.Migrations
{
    [DbContext(typeof(ToolDbContext))]
    [Migration("20240531035704_diachicsNotnull")]
    partial class diachicsNotnull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThietBiDienTu_2.Models.Chitietphieumuon", b =>
                {
                    b.Property<int>("Mapm")
                        .HasColumnType("int")
                        .HasColumnName("MAPM");

                    b.Property<int>("Matb")
                        .HasColumnType("int")
                        .HasColumnName("MATB");

                    b.Property<DateTime?>("Ngaytra")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTRA");

                    b.HasKey("Mapm", "Matb");

                    b.HasIndex(new[] { "Matb" }, "IX_CHITIETPHIEUMUON_IDCTTB");

                    b.ToTable("CHITIETPHIEUMUON", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Chitietphieusua", b =>
                {
                    b.Property<int>("Maps")
                        .HasColumnType("int")
                        .HasColumnName("MAPS");

                    b.Property<int>("Matb")
                        .HasColumnType("int")
                        .HasColumnName("MATB");

                    b.Property<decimal?>("Chiphi")
                        .HasColumnType("money")
                        .HasColumnName("CHIPHI");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MOTA");

                    b.Property<DateTime?>("Ngayhoanthanh")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYHOANTHANH");

                    b.HasKey("Maps", "Matb");

                    b.HasIndex(new[] { "Matb" }, "IX_CHITIETPHIEUSUA_IDCTTB");

                    b.ToTable("CHITIETPHIEUSUA", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Coso", b =>
                {
                    b.Property<int>("Macs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MACS");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Macs"));

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Tencs")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENCS");

                    b.HasKey("Macs")
                        .HasName("PK__COSO__603F183B80D63A70");

                    b.ToTable("COSO", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Dongthietbi", b =>
                {
                    b.Property<int>("Madongtb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MADONGTB");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Madongtb"));

                    b.Property<string>("Hinhanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HINHANH");

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MOTA");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<string>("Tendongtb")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENDONGTB");

                    b.HasKey("Madongtb")
                        .HasName("PK__THIETBI__6023721DFE47CEB0");

                    b.ToTable("DONGTHIETBI", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Khoa", b =>
                {
                    b.Property<int>("Makhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAKHOA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Makhoa"));

                    b.Property<string>("Tenkhoa")
                        .IsRequired()
                        .HasMaxLength(55)
                        .HasColumnType("nvarchar(55)")
                        .HasColumnName("TENKHOA");

                    b.HasKey("Makhoa");

                    b.ToTable("KHOA", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Nganh", b =>
                {
                    b.Property<int>("Manganh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MANGANH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Manganh"));

                    b.Property<string>("Tennganh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENNGANH");

                    b.HasKey("Manganh");

                    b.ToTable("NGANH", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Nhanvien", b =>
                {
                    b.Property<int>("Manv")
                        .HasColumnType("int")
                        .HasColumnName("MANV");

                    b.Property<string>("Diachi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Gioitinh")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("GIOITINH");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tennv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENNV");

                    b.HasKey("Manv")
                        .HasName("PK__NHANVIEN__603F511441B78137");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phieumuon", b =>
                {
                    b.Property<int>("Mapm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAPM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mapm"));

                    b.Property<string>("LydoHuy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LYDOHUY");

                    b.Property<string>("LydoTuChoi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LYDOTUCHOI");

                    b.Property<string>("Lydomuon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LYDOMUON")
                        .HasDefaultValueSql("(N'')");

                    b.Property<int?>("Manv")
                        .HasColumnType("int")
                        .HasColumnName("MANV");

                    b.Property<int>("Masv")
                        .HasColumnType("int")
                        .HasColumnName("MASV");

                    b.Property<DateTime>("Ngaylap")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYLAP");

                    b.Property<DateTime>("Ngaymuon")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYMUON");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Mapm")
                        .HasName("PK__PHIEUMUO__603F61CDEBB7FD91");

                    b.HasIndex(new[] { "Manv" }, "IX_PHIEUMUON_MANV");

                    b.HasIndex(new[] { "Masv" }, "IX_PHIEUMUON_MASV");

                    b.ToTable("PHIEUMUON", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phieusua", b =>
                {
                    b.Property<int>("Maps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAPS");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Maps"));

                    b.Property<DateTime>("Ngaylap")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYLAP");

                    b.Property<decimal?>("Tongchiphi")
                        .HasColumnType("money")
                        .HasColumnName("TONGCHIPHI");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Maps");

                    b.ToTable("PHIEUSUA", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phong", b =>
                {
                    b.Property<string>("Map")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MAP");

                    b.Property<int?>("Douutien")
                        .HasColumnType("int")
                        .HasColumnName("DOUUTIEN");

                    b.Property<string>("Loaiphong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LOAIPHONG");

                    b.Property<int>("Macs")
                        .HasColumnType("int")
                        .HasColumnName("MACS");

                    b.Property<string>("Tenphong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENPHONG");

                    b.HasKey("Map")
                        .HasName("PK__PHONG__C790778043DD78DD");

                    b.HasIndex(new[] { "Macs" }, "IX_PHONG_MACS");

                    b.ToTable("PHONG", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Sinhvien", b =>
                {
                    b.Property<int>("Masv")
                        .HasColumnType("int")
                        .HasColumnName("MASV");

                    b.Property<string>("Diachi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Gioitinh")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("GIOITINH")
                        .HasDefaultValueSql("(N'')");

                    b.Property<int>("Makhoa")
                        .HasColumnType("int")
                        .HasColumnName("MAKHOA");

                    b.Property<int>("Manganh")
                        .HasColumnType("int")
                        .HasColumnName("MANGANH");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tensv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENSV");

                    b.HasKey("Masv")
                        .HasName("PK__SINHVIEN__60228A2812E98CDF");

                    b.HasIndex("Makhoa");

                    b.HasIndex("Manganh");

                    b.ToTable("SINHVIEN", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Taikhoan", b =>
                {
                    b.Property<int>("Matk")
                        .HasColumnType("int")
                        .HasColumnName("MATK");

                    b.Property<short>("Loaitk")
                        .HasColumnType("smallint")
                        .HasColumnName("LOAITK");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MATKHAU");

                    b.HasKey("Matk")
                        .HasName("PK__ACCOUNT__6029121DD1D4BE32");

                    b.ToTable("TAIKHOAN", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Thietbi", b =>
                {
                    b.Property<int>("Matb")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MATB");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Matb"));

                    b.Property<int>("Madongtb")
                        .HasColumnType("int")
                        .HasColumnName("MADONGTB");

                    b.Property<string>("Map")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MAP");

                    b.Property<string>("Seri")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SERI");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Matb")
                        .HasName("PK_CHITIETTHIETBI");

                    b.HasIndex(new[] { "Map" }, "IX_CHITIETTHIETBI_MAP");

                    b.HasIndex(new[] { "Madongtb" }, "IX_CHITIETTHIETBI_MATB");

                    b.ToTable("THIETBI", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Chitietphieumuon", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Phieumuon", "MapmNavigation")
                        .WithMany("Chitietphieumuons")
                        .HasForeignKey("Mapm")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETPHIEUMUON_PHIEUMUON1");

                    b.HasOne("ThietBiDienTu_2.Models.Thietbi", "MatbNavigation")
                        .WithMany("Chitietphieumuons")
                        .HasForeignKey("Matb")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETPHIEUMUON_CHITIETTHIETBI");

                    b.Navigation("MapmNavigation");

                    b.Navigation("MatbNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Chitietphieusua", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Phieusua", "MapsNavigation")
                        .WithMany("Chitietphieusuas")
                        .HasForeignKey("Maps")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETPHIEUSUA_PHIEUSUA1");

                    b.HasOne("ThietBiDienTu_2.Models.Thietbi", "MatbNavigation")
                        .WithMany("Chitietphieusuas")
                        .HasForeignKey("Matb")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETPHIEUSUA_CHITIETTHIETBI");

                    b.Navigation("MapsNavigation");

                    b.Navigation("MatbNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Nhanvien", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Taikhoan", "ManvNavigation")
                        .WithOne("Nhanvien")
                        .HasForeignKey("ThietBiDienTu_2.Models.Nhanvien", "Manv")
                        .IsRequired()
                        .HasConstraintName("FK__ACCOUNT__NV");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phieumuon", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Nhanvien", "ManvNavigation")
                        .WithMany("Phieumuons")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FK_PHIEUMUON_NHANVIEN1");

                    b.HasOne("ThietBiDienTu_2.Models.Sinhvien", "MasvNavigation")
                        .WithMany("Phieumuons")
                        .HasForeignKey("Masv")
                        .IsRequired()
                        .HasConstraintName("FK_PHIEUMUON_SINHVIEN");

                    b.Navigation("ManvNavigation");

                    b.Navigation("MasvNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phong", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Coso", "MacsNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("Macs")
                        .IsRequired()
                        .HasConstraintName("FK__PHONG__MACS__5165187F");

                    b.Navigation("MacsNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Sinhvien", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Khoa", "MakhoaNavigation")
                        .WithMany("Sinhviens")
                        .HasForeignKey("Makhoa")
                        .IsRequired()
                        .HasConstraintName("FK_SINHVIEN_KHOA");

                    b.HasOne("ThietBiDienTu_2.Models.Nganh", "ManganhNavigation")
                        .WithMany("Sinhviens")
                        .HasForeignKey("Manganh")
                        .IsRequired()
                        .HasConstraintName("FK_SINHVIEN_NGANH");

                    b.HasOne("ThietBiDienTu_2.Models.Taikhoan", "MasvNavigation")
                        .WithOne("Sinhvien")
                        .HasForeignKey("ThietBiDienTu_2.Models.Sinhvien", "Masv")
                        .IsRequired()
                        .HasConstraintName("FK__ACCOUNT__SV");

                    b.Navigation("MakhoaNavigation");

                    b.Navigation("ManganhNavigation");

                    b.Navigation("MasvNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Thietbi", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Dongthietbi", "MadongtbNavigation")
                        .WithMany("Thietbis")
                        .HasForeignKey("Madongtb")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETTHIETBI_THIETBI");

                    b.HasOne("ThietBiDienTu_2.Models.Phong", "MapNavigation")
                        .WithMany("Thietbis")
                        .HasForeignKey("Map")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETTHIETBI_PHONG");

                    b.Navigation("MadongtbNavigation");

                    b.Navigation("MapNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Coso", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Dongthietbi", b =>
                {
                    b.Navigation("Thietbis");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Khoa", b =>
                {
                    b.Navigation("Sinhviens");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Nganh", b =>
                {
                    b.Navigation("Sinhviens");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Nhanvien", b =>
                {
                    b.Navigation("Phieumuons");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phieumuon", b =>
                {
                    b.Navigation("Chitietphieumuons");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phieusua", b =>
                {
                    b.Navigation("Chitietphieusuas");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phong", b =>
                {
                    b.Navigation("Thietbis");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Sinhvien", b =>
                {
                    b.Navigation("Phieumuons");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Taikhoan", b =>
                {
                    b.Navigation("Nhanvien");

                    b.Navigation("Sinhvien");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Thietbi", b =>
                {
                    b.Navigation("Chitietphieumuons");

                    b.Navigation("Chitietphieusuas");
                });
#pragma warning restore 612, 618
        }
    }
}
