// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThietBiDienTu_2.Models;

#nullable disable

namespace ThietBiDienTu_2.Migrations
{
    [DbContext(typeof(ToolDbContext))]
    [Migration("20240306013607_v0")]
    partial class v0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThietBiDienTu_2.Models.Account", b =>
                {
                    b.Property<int>("Username")
                        .HasColumnType("int")
                        .HasColumnName("USERNAME");

                    b.Property<short>("Loaiuser")
                        .HasColumnType("smallint")
                        .HasColumnName("LOAIUSER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PASSWORD");

                    b.HasKey("Username")
                        .HasName("PK__ACCOUNT__6029121DD1D4BE32");

                    b.ToTable("ACCOUNT", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Chitietphieumuon", b =>
                {
                    b.Property<int>("Mapm")
                        .HasColumnType("int")
                        .HasColumnName("MAPM");

                    b.Property<string>("Seri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SERI");

                    b.Property<DateTime?>("Ngaytra")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYTRA");

                    b.HasKey("Mapm", "Seri");

                    b.HasIndex("Seri");

                    b.ToTable("CHITIETPHIEUMUON", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Chitietthietbi", b =>
                {
                    b.Property<string>("Seri")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SERI");

                    b.Property<string>("Maloai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MALOAI")
                        .IsFixedLength();

                    b.Property<string>("Map")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MAP");

                    b.Property<string>("Matb")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MATB");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Seri");

                    b.HasIndex("Map");

                    b.HasIndex("Matb");

                    b.ToTable("CHITIETTHIETBI", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Coso", b =>
                {
                    b.Property<int>("Macs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MACS");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Macs"));

                    b.Property<string>("Diachi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Tencs")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENCS");

                    b.HasKey("Macs")
                        .HasName("PK__COSO__603F183B80D63A70");

                    b.ToTable("COSO", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Loaithietbi", b =>
                {
                    b.Property<string>("Maloai")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MALOAI")
                        .IsFixedLength();

                    b.Property<string>("Tenloai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TENLOAI");

                    b.HasKey("Maloai");

                    b.ToTable("LOAITHIETBI", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Nhanvien", b =>
                {
                    b.Property<int>("Manv")
                        .HasColumnType("int")
                        .HasColumnName("MANV");

                    b.Property<string>("Diachi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Gioitinh")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("GIOITINH");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tennv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENNV");

                    b.HasKey("Manv")
                        .HasName("PK__NHANVIEN__603F511441B78137");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phieumuon", b =>
                {
                    b.Property<int>("Mapm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAPM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mapm"));

                    b.Property<int>("Manv")
                        .HasColumnType("int")
                        .HasColumnName("MANV");

                    b.Property<int>("Masv")
                        .HasColumnType("int")
                        .HasColumnName("MASV");

                    b.Property<DateTime>("Ngaylap")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYLAP");

                    b.Property<DateTime?>("Ngaymuon")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYMUON");

                    b.Property<string>("Trangthai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Mapm")
                        .HasName("PK__PHIEUMUO__603F61CDEBB7FD91");

                    b.HasIndex("Manv");

                    b.HasIndex("Masv");

                    b.ToTable("PHIEUMUON", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phong", b =>
                {
                    b.Property<string>("Map")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MAP");

                    b.Property<string>("Loaiphong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LOAIPHONG");

                    b.Property<int>("Macs")
                        .HasColumnType("int")
                        .HasColumnName("MACS");

                    b.Property<string>("Tenphong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENPHONG");

                    b.HasKey("Map")
                        .HasName("PK__PHONG__C790778043DD78DD");

                    b.HasIndex("Macs");

                    b.ToTable("PHONG", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Sinhvien", b =>
                {
                    b.Property<int>("Masv")
                        .HasColumnType("int")
                        .HasColumnName("MASV");

                    b.Property<string>("Diachi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DIACHI");

                    b.Property<int?>("Diemrenluyen")
                        .HasColumnType("int")
                        .HasColumnName("DIEMRENLUYEN");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Gioitinh")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("GIOITINH")
                        .HasDefaultValueSql("(N'')");

                    b.Property<string>("Khoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("KHOA");

                    b.Property<string>("Nganh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NGANH");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tensv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENSV");

                    b.HasKey("Masv")
                        .HasName("PK__SINHVIEN__60228A2812E98CDF");

                    b.ToTable("SINHVIEN", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Thietbi", b =>
                {
                    b.Property<string>("Matb")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MATB");

                    b.Property<string>("Hinhanh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HINHANH");

                    b.Property<string>("Maloai")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MALOAI")
                        .IsFixedLength();

                    b.Property<string>("Mota")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MOTA");

                    b.Property<int>("Soluong")
                        .HasColumnType("int")
                        .HasColumnName("SOLUONG");

                    b.Property<string>("Tenthietbi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENTHIETBI");

                    b.HasKey("Matb")
                        .HasName("PK__THIETBI__6023721DFE47CEB0");

                    b.HasIndex("Maloai");

                    b.ToTable("THIETBI", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Chitietphieumuon", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Phieumuon", "MapmNavigation")
                        .WithMany("Chitietphieumuons")
                        .HasForeignKey("Mapm")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETPHIEUMUON_PHIEUMUON1");

                    b.HasOne("ThietBiDienTu_2.Models.Chitietthietbi", "SeriNavigation")
                        .WithMany("Chitietphieumuons")
                        .HasForeignKey("Seri")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETPHIEUMUON_CHITIETTHIETBI");

                    b.Navigation("MapmNavigation");

                    b.Navigation("SeriNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Chitietthietbi", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Phong", "MapNavigation")
                        .WithMany("Chitietthietbis")
                        .HasForeignKey("Map")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETTHIETBI_PHONG");

                    b.HasOne("ThietBiDienTu_2.Models.Thietbi", "MatbNavigation")
                        .WithMany("Chitietthietbis")
                        .HasForeignKey("Matb")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETTHIETBI_THIETBI");

                    b.Navigation("MapNavigation");

                    b.Navigation("MatbNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Nhanvien", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Account", "ManvNavigation")
                        .WithOne("Nhanvien")
                        .HasForeignKey("ThietBiDienTu_2.Models.Nhanvien", "Manv")
                        .IsRequired()
                        .HasConstraintName("FK__ACCOUNT__NV");

                    b.Navigation("ManvNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phieumuon", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Nhanvien", "ManvNavigation")
                        .WithMany("Phieumuons")
                        .HasForeignKey("Manv")
                        .IsRequired()
                        .HasConstraintName("FK_PHIEUMUON_NHANVIEN1");

                    b.HasOne("ThietBiDienTu_2.Models.Sinhvien", "MasvNavigation")
                        .WithMany("Phieumuons")
                        .HasForeignKey("Masv")
                        .IsRequired()
                        .HasConstraintName("FK_PHIEUMUON_SINHVIEN");

                    b.Navigation("ManvNavigation");

                    b.Navigation("MasvNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phong", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Coso", "MacsNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("Macs")
                        .IsRequired()
                        .HasConstraintName("FK__PHONG__MACS__5165187F");

                    b.Navigation("MacsNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Sinhvien", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Account", "MasvNavigation")
                        .WithOne("Sinhvien")
                        .HasForeignKey("ThietBiDienTu_2.Models.Sinhvien", "Masv")
                        .IsRequired()
                        .HasConstraintName("FK__ACCOUNT__SV");

                    b.Navigation("MasvNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Thietbi", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Loaithietbi", "MaloaiNavigation")
                        .WithMany("Thietbis")
                        .HasForeignKey("Maloai")
                        .HasConstraintName("FK_THIETBI_LOAITHIETBI");

                    b.Navigation("MaloaiNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Account", b =>
                {
                    b.Navigation("Nhanvien");

                    b.Navigation("Sinhvien");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Chitietthietbi", b =>
                {
                    b.Navigation("Chitietphieumuons");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Coso", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Loaithietbi", b =>
                {
                    b.Navigation("Thietbis");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Nhanvien", b =>
                {
                    b.Navigation("Phieumuons");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phieumuon", b =>
                {
                    b.Navigation("Chitietphieumuons");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phong", b =>
                {
                    b.Navigation("Chitietthietbis");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Sinhvien", b =>
                {
                    b.Navigation("Phieumuons");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Thietbi", b =>
                {
                    b.Navigation("Chitietthietbis");
                });
#pragma warning restore 612, 618
        }
    }
}
