// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThietBiDienTu_2.Models;

#nullable disable

namespace ThietBiDienTu_2.Migrations
{
    [DbContext(typeof(ToolDbContext))]
    partial class ToolDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThietBiDienTu_2.Models.Chitietphieumuon", b =>
                {
                    b.Property<int>("Mactpm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MACTPM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mactpm"));

                    b.Property<int>("Mapm")
                        .HasColumnType("int")
                        .HasColumnName("MAPM");

                    b.Property<string>("Matb")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MATB");

                    b.HasKey("Mactpm")
                        .HasName("PK__CHITIETP__F50D75CA51DA8B28");

                    b.HasIndex("Mapm");

                    b.HasIndex("Matb");

                    b.ToTable("CHITIETPHIEUMUON", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Coso", b =>
                {
                    b.Property<int>("Macs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MACS");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Macs"));

                    b.Property<string>("Tencs")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENCS");

                    b.HasKey("Macs")
                        .HasName("PK__COSO__603F183BED1C350F");

                    b.ToTable("COSO", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Nhanvien", b =>
                {
                    b.Property<int>("Manv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MANV");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Manv"));

                    b.Property<string>("Diachi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Phai")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("PHAI");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tennv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENNV");

                    b.HasKey("Manv")
                        .HasName("PK__NHANVIEN__603F5114894AC6CF");

                    b.ToTable("NHANVIEN", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phieumuon", b =>
                {
                    b.Property<int>("Mapm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MAPM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mapm"));

                    b.Property<int?>("Manv")
                        .HasColumnType("int")
                        .HasColumnName("MANV");

                    b.Property<int>("Masv")
                        .HasColumnType("int")
                        .HasColumnName("MASV");

                    b.Property<DateTime>("Ngaylap")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYLAP");

                    b.HasKey("Mapm")
                        .HasName("PK__PHIEUMUO__603F61CDEBB7FD91");

                    b.HasIndex("Manv");

                    b.HasIndex("Masv");

                    b.ToTable("PHIEUMUON", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phong", b =>
                {
                    b.Property<string>("Map")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MAP");

                    b.Property<string>("Loaiphong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LOAIPHONG");

                    b.Property<int>("Macs")
                        .HasColumnType("int")
                        .HasColumnName("MACS");

                    b.Property<string>("Tenphong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENPHONG");

                    b.HasKey("Map")
                        .HasName("PK__PHONG__C7907780ED66A93B");

                    b.HasIndex("Macs");

                    b.ToTable("PHONG", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Sinhvien", b =>
                {
                    b.Property<int>("Masv")
                        .HasColumnType("int")
                        .HasColumnName("MASV");

                    b.Property<string>("Diachi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DIACHI");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Khoa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("KHOA");

                    b.Property<string>("Nganh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NGANH");

                    b.Property<DateTime>("Ngaysinh")
                        .HasColumnType("datetime")
                        .HasColumnName("NGAYSINH");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("SDT");

                    b.Property<string>("Tensv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENSV");

                    b.HasKey("Masv")
                        .HasName("PK__SINHVIEN__60228A2838C40CEB");

                    b.ToTable("SINHVIEN", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Thietbi", b =>
                {
                    b.Property<string>("Matb")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MATB");

                    b.Property<string>("Map")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("MAP");

                    b.Property<string>("Tenthietbi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("TENTHIETBI");

                    b.Property<string>("Trangthai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TRANGTHAI");

                    b.HasKey("Matb")
                        .HasName("PK__THIETBI__6023721DD1D4DC00");

                    b.HasIndex("Map");

                    b.ToTable("THIETBI", (string)null);
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Chitietphieumuon", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Phieumuon", "MapmNavigation")
                        .WithMany("Chitietphieumuons")
                        .HasForeignKey("Mapm")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETPHIEUMUON_PHIEUMUON1");

                    b.HasOne("ThietBiDienTu_2.Models.Thietbi", "MatbNavigation")
                        .WithMany("Chitietphieumuons")
                        .HasForeignKey("Matb")
                        .IsRequired()
                        .HasConstraintName("FK_CHITIETPHIEUMUON_THIETBI");

                    b.Navigation("MapmNavigation");

                    b.Navigation("MatbNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phieumuon", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Nhanvien", "ManvNavigation")
                        .WithMany("Phieumuons")
                        .HasForeignKey("Manv")
                        .HasConstraintName("FK_PHIEUMUON_NHANVIEN1");

                    b.HasOne("ThietBiDienTu_2.Models.Sinhvien", "MasvNavigation")
                        .WithMany("Phieumuons")
                        .HasForeignKey("Masv")
                        .IsRequired()
                        .HasConstraintName("FK_PHIEUMUON_SINHVIEN");

                    b.Navigation("ManvNavigation");

                    b.Navigation("MasvNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phong", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Coso", "MacsNavigation")
                        .WithMany("Phongs")
                        .HasForeignKey("Macs")
                        .IsRequired()
                        .HasConstraintName("FK__PHONG__MACS__3D5E1FD2");

                    b.Navigation("MacsNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Thietbi", b =>
                {
                    b.HasOne("ThietBiDienTu_2.Models.Phong", "MapNavigation")
                        .WithMany("Thietbis")
                        .HasForeignKey("Map")
                        .IsRequired()
                        .HasConstraintName("FK__THIETBI__MAP__403A8C7D");

                    b.Navigation("MapNavigation");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Coso", b =>
                {
                    b.Navigation("Phongs");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Nhanvien", b =>
                {
                    b.Navigation("Phieumuons");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phieumuon", b =>
                {
                    b.Navigation("Chitietphieumuons");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Phong", b =>
                {
                    b.Navigation("Thietbis");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Sinhvien", b =>
                {
                    b.Navigation("Phieumuons");
                });

            modelBuilder.Entity("ThietBiDienTu_2.Models.Thietbi", b =>
                {
                    b.Navigation("Chitietphieumuons");
                });
#pragma warning restore 612, 618
        }
    }
}
